# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'double.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(997, 853)
        TabWidget.setMinimumSize(QtCore.QSize(0, 0))
        TabWidget.setStyleSheet("background:rgb(52, 52, 52)")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("background:rgb(218, 218, 218);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 40, 341, 591))
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setMinimumSize(QtCore.QSize(381, 651))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("background:rgb(218, 218, 218);")
        self.groupBox_6.setObjectName("groupBox_6")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 40, 341, 591))
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_4.addWidget(self.groupBox_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        TabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox_2.setStyleSheet("    \n"
"      QGroupBox {\n"
"            border-color:rgb(82, 165, 247);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }\n"
"     \n"
"      QGroupBox {\n"
"            background-color:rgb(24,26,51);\n"
"\n"
"        }")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(10, 5, 10, 15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pushButton_2.setPalette(palette)
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_2.setAutoRepeatDelay(300)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("\n"
"background-color:rgb(97, 97, 97);\n"
"color:rgb(249, 249, 249)\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 350))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 350))
        self.groupBox_3.setStyleSheet("    \n"
"      QGroupBox {\n"
"            border-color:rgb(82, 165, 247);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }\n"
"     \n"
"      QGroupBox {\n"
"            background-color:rgb(24,26,51);\n"
"\n"
"        }")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 315))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 218, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textEdit_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background:rgb(218, 218, 218);\n"
"")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_2.setLineWidth(3)
        self.textEdit_2.setMidLineWidth(1)
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(75, 31))
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 31))
        self.pushButton_5.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 400))
        self.groupBox_4.setStyleSheet("    \n"
"      QGroupBox {\n"
"            border-color:rgb(82, 165, 247);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }\n"
"     \n"
"      QGroupBox {\n"
"            background-color:rgb(24,26,51);\n"
"\n"
"        }")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 20)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 309))
        self.textEdit.setStyleSheet("background:rgb(218, 218, 218);\n"
"")
        self.textEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit.setLineWidth(3)
        self.textEdit.setMidLineWidth(1)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(75, 31))
        self.pushButton_4.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(75, 31))
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.groupBox_2.raise_()
        TabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 45))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.groupBox.setStyleSheet("    \n"
"      QGroupBox {\n"
"            border-color:rgb(82, 165, 247);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }\n"
"     \n"
"      QGroupBox {\n"
"            background-color:rgb(24,26,51);\n"
"\n"
"        }")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setContentsMargins(-1, 5, 105, 10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 31))
        self.pushButton_6.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_6.setAutoRepeatDelay(200)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_2.setStyleSheet("\n"
"background-color:rgb(97, 97, 97);\n"
"color:rgb(249, 249, 249)\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton_7.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 65))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_7.setStyleSheet("    \n"
"      QGroupBox {\n"
"            border-color:rgb(82, 165, 247);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }\n"
"     \n"
"      QGroupBox {\n"
"            background-color:rgb(24,26,51);\n"
"\n"
"        }")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_6.setContentsMargins(5, 5, 105, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 45))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_3.setPalette(palette)
        self.label_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label_3.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setStyleSheet("\n"
"background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255)\n"
"")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setLineWidth(5)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setIndent(3)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("\n"
"background-color:rgb(97, 97, 97);\n"
"color:rgb(249, 249, 249);\n"
"\n"
"\n"
"    caret-color: red;\n"
"\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton_12.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        icon = QtGui.QIcon.fromTheme("111")
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 65))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_8.setStyleSheet("    \n"
"      QGroupBox {\n"
"            border-color:rgb(82, 165, 247);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }\n"
"     \n"
"      QGroupBox {\n"
"            background-color:rgb(24,26,51);\n"
"\n"
"        }")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_7.setContentsMargins(-1, -1, 105, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label_4.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setStyleSheet("\n"
"background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255)\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setLineWidth(5)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("\n"
"background-color:rgb(97, 97, 97);\n"
"color:rgb(249, 249, 249)\n"
"")
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton_9.setMouseTracking(True)
        self.pushButton_9.setTabletTracking(False)
        self.pushButton_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_9.setAutoRepeatDelay(600)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_7.addWidget(self.pushButton_9)
        self.verticalLayout_5.addWidget(self.groupBox_8)
        self.progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_5.addWidget(self.progressBar)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 260))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 260))
        self.groupBox_9.setStyleSheet("    \n"
"      QGroupBox {\n"
"            border-color:rgb(82, 165, 247);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }\n"
"     \n"
"      QGroupBox {\n"
"            background-color:rgb(24,26,51);\n"
"\n"
"        }")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_5.sizePolicy().hasHeightForWidth())
        self.textEdit_5.setSizePolicy(sizePolicy)
        self.textEdit_5.setMaximumSize(QtCore.QSize(10777215, 10777215))
        self.textEdit_5.setMouseTracking(False)
        self.textEdit_5.setStyleSheet("background:rgb(218, 218, 218);\n"
"")
        self.textEdit_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_5.setLineWidth(5)
        self.textEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_5.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_5.setReadOnly(True)
        self.textEdit_5.setObjectName("textEdit_5")
        self.horizontalLayout_9.addWidget(self.textEdit_5)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_8.setMinimumSize(QtCore.QSize(76, 31))
        self.pushButton_8.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_9.addWidget(self.pushButton_8)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 230))
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 230))
        self.groupBox_10.setStyleSheet("    \n"
"      QGroupBox {\n"
"            border-color:rgb(82, 165, 247);\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"        }\n"
"     \n"
"      QGroupBox {\n"
"            background-color:rgb(24,26,51);\n"
"\n"
"        }")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.textEdit_6 = QtWidgets.QTextEdit(self.groupBox_10)
        self.textEdit_6.setStyleSheet("background:rgb(218, 218, 218);\n"
"")
        self.textEdit_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_6.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_6.setReadOnly(True)
        self.textEdit_6.setObjectName("textEdit_6")
        self.horizontalLayout_8.addWidget(self.textEdit_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_10.setMinimumSize(QtCore.QSize(76, 31))
        self.pushButton_10.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_10.setAutoRepeatDelay(296)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_13.setMinimumSize(QtCore.QSize(76, 31))
        self.pushButton_13.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_4.addWidget(self.pushButton_13)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_11.setMinimumSize(QtCore.QSize(76, 31))
        self.pushButton_11.setStyleSheet("QPushButton\n"
"{background-color:rgb(0, 0, 91);\n"
"color:rgb(255, 255, 255);\n"
"border:rgb(226, 226, 226);\n"
"       border-width: 1px;\n"
"            border-style: solid;\n"
"            margin-top: 0.5ex;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgba(170, 250, 250, 250), stop:1 rgba(0, 255, 255, 255));\n"
"border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"color:rgb(0, 0, 127)\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_4.addWidget(self.pushButton_11)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.groupBox_10)
        TabWidget.addTab(self.tab_2, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(2)
        self.pushButton_3.clicked.connect(self.textEdit.clear)
        self.pushButton_5.clicked.connect(self.textEdit_2.clear)
        self.pushButton_11.clicked.connect(self.textEdit_6.clear)
        self.pushButton_8.clicked.connect(self.textEdit_5.clear)
        self.pushButton_6.clicked.connect(self.lineEdit_2.clear)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "广告mock小工具"))
        self.groupBox_5.setTitle(_translate("TabWidget", "IOS"))
        self.textEdit_3.setHtml(_translate("TabWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#aa0000;\">支持类型</span><span style=\" font-size:16pt;\">：全部IOS手机</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\"><br /></span><span style=\" font-size:16pt; color:#aa0000;\">准备工作</span><span style=\" font-size:16pt;\">：打开斗鱼App</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\"><br /></span><span style=\" font-size:16pt; color:#ff0000;\">操作步骤</span><span style=\" font-size:16pt;\">：</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">1.输入需要mock的广告位posid</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">2.输入手机ip，点击连接。<br />3.点击执行。<br />4.可以根据具体需要切换环境。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\"><br /></span><span style=\" font-size:16pt; color:#aa0000;\">注意事项</span><span style=\" font-size:16pt;\">：执行后，重启斗鱼。</span></p></body></html>"))
        self.groupBox_6.setTitle(_translate("TabWidget", "Android"))
        self.textEdit_4.setHtml(_translate("TabWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#aa0000;\">支持类型</span><span style=\" font-size:16pt;\">：全部安卓手机。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\"><br /></span><span style=\" font-size:16pt; color:#aa0000;\">准备工作</span><span style=\" font-size:16pt;\">：需要打开开发者设置，数据线连接到电脑。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\"><br /></span><span style=\" font-size:16pt; color:#aa0000;\">操作步骤</span><span style=\" font-size:16pt;\">：</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">1.输入需要mock的广告位posid，点击查询<br />2.点击执行。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\"><br /></span><span style=\" font-size:16pt; color:#aa0000;\">注意事项</span><span style=\" font-size:16pt;\">：执行后，重启斗鱼。</span></p></body></html>"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "帮助"))
        self.pushButton_2.setText(_translate("TabWidget", "清除"))
        self.lineEdit.setPlaceholderText(_translate("TabWidget", "输入posid查询"))
        self.pushButton.setText(_translate("TabWidget", "查询"))
        self.textEdit_2.setHtml(_translate("TabWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'方正舒体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_5.setText(_translate("TabWidget", "清除"))
        self.pushButton_4.setText(_translate("TabWidget", "执行"))
        self.pushButton_3.setText(_translate("TabWidget", "清除"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Android"))
        self.pushButton_6.setText(_translate("TabWidget", "清除"))
        self.lineEdit_2.setPlaceholderText(_translate("TabWidget", "输入posid查询"))
        self.pushButton_7.setText(_translate("TabWidget", "查询"))
        self.label_3.setText(_translate("TabWidget", "本机IP"))
        self.lineEdit_3.setPlaceholderText(_translate("TabWidget", "输入手机IP"))
        self.pushButton_12.setText(_translate("TabWidget", "连接"))
        self.label_4.setText(_translate("TabWidget", "切换环境"))
        self.comboBox.setItemText(0, _translate("TabWidget", "联调站"))
        self.comboBox.setItemText(1, _translate("TabWidget", "live站"))
        self.comboBox.setItemText(2, _translate("TabWidget", "预发布站"))
        self.comboBox.setItemText(3, _translate("TabWidget", "正式站"))
        self.pushButton_9.setText(_translate("TabWidget", "切换"))
        self.pushButton_8.setText(_translate("TabWidget", "清除"))
        self.pushButton_10.setText(_translate("TabWidget", "执行"))
        self.pushButton_13.setText(_translate("TabWidget", "关闭Mock"))
        self.pushButton_11.setText(_translate("TabWidget", "清除"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "IOS"))
